name: Publish to TestPyPI

on:
  workflow_dispatch:
  push:
    # by branch
    branches:
        - v*
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC
      contents: read

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check commit message
        if: github.event_name != 'workflow_dispatch'
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          if [[ ! "$COMMIT_MSG" =~ ^(fix|feat|ref).*$ ]]; then
            echo "Skipping workflow: commit message does not start with a valid conventional commit type."
            exit 78
          fi
        shell: bash

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build package
        run: |
          python -m pip install --upgrade build
          python -m build

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          # No username/password needed; OIDC is used automatically
